### ISSUE TITLE
Why doesn't the Google Cloud APIs have a high (<10 liner) or low (>10 liner) level number of boilerplate line of code?

### ISSUE THREAD

**Issue by shyamalschandra** [googleapis/java-texttospeech#41]
Why doesn't the [language-specific APIs](https://cloud.google.com/text-to-speech/docs/apis) have a high (<10 liner) or low (>10 liner) level number of boilerplate lines of code to get Cloud Text-to-Speech running without much hassle?  It seems like very convoluted directions and very nonlinear withotu paid 24/7 technical support?

**Comment by b-loved-dreamer** [comment]
Thank you for filing this issue. We asked some clarifying questions a week or more ago and never heard back from you. We are unable to proceed with this issue until then, so we are closing it. Please feel free to re-open this issue with more information.
